import React from 'react';
import { User, Shield, Phone, Mail } from 'lucide-react';

const TeamExportCard = ({ team, players, auctionName, refProp }) => {
    return (
        <div ref={refProp} style={{ width: '800px', padding: '40px', background: 'linear-gradient(135deg, #0f172a 0%, #1e293b 100%)', color: 'white', fontFamily: "'Segoe UI', sans-serif", position: 'relative', overflow: 'hidden' }}>

            {/* Watermark / Background Decoration */}
            <div style={{ position: 'absolute', top: '-50px', right: '-50px', width: '300px', height: '300px', background: 'rgba(255,255,255,0.03)', borderRadius: '50%' }}></div>
            <div style={{ position: 'absolute', bottom: '-100px', left: '-100px', width: '400px', height: '400px', background: 'rgba(255,255,255,0.02)', borderRadius: '50%' }}></div>

            {/* Header */}
            <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', borderBottom: '2px solid rgba(255,255,255,0.1)', paddingBottom: '20px', marginBottom: '30px' }}>
                <div style={{ display: 'flex', alignItems: 'center', gap: '20px' }}>
                    <div style={{ width: '100px', height: '100px', background: 'white', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden', border: '4px solid rgba(255,255,255,0.2)' }}>
                        {team.logoUrl ? <img src={team.logoUrl} alt="Team Logo" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <Shield size={50} color="#1e293b" />}
                    </div>
                    <div>
                        <h1 style={{ margin: 0, fontSize: '2.5rem', textTransform: 'uppercase', letterSpacing: '2px' }}>{team.name}</h1>
                        <p style={{ margin: '5px 0 0 0', opacity: 0.7, fontSize: '1.2rem' }}>{auctionName || "Auction Squad"}</p>
                    </div>
                </div>
                <div style={{ textAlign: 'right' }}>
                    <div style={{ fontSize: '1rem', opacity: 0.6, textTransform: 'uppercase' }}>Owner</div>
                    <div style={{ fontSize: '1.5rem', fontWeight: 'bold', color: '#4ade80' }}>{team.ownerName}</div>
                </div>
            </div>

            {/* Squad List */}
            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '15px' }}>
                {players && players.length > 0 ? (
                    players.map((p, index) => (
                        <div key={index} style={{ background: 'rgba(255,255,255,0.05)', padding: '15px', borderRadius: '10px', display: 'flex', alignItems: 'center', gap: '15px', border: '1px solid rgba(255,255,255,0.05)' }}>
                            <div style={{ width: '50px', height: '50px', background: '#334155', borderRadius: '50%', display: 'flex', alignItems: 'center', justifyContent: 'center', overflow: 'hidden' }}>
                                {p.image ? <img src={p.image} alt="" style={{ width: '100%', height: '100%', objectFit: 'cover' }} /> : <User size={24} color="#94a3b8" />}
                            </div>
                            <div>
                                <div style={{ fontWeight: 'bold', fontSize: '1.1rem' }}>{p.name}</div>
                                <div style={{ fontSize: '0.85rem', opacity: 0.7, display: 'flex', gap: '10px' }}>
                                    <span style={{ textTransform: 'uppercase', background: 'rgba(255,255,255,0.1)', padding: '2px 6px', borderRadius: '4px' }}>{p.role || "Player"}</span>
                                    {p.soldPrice && <span style={{ color: '#fbbf24' }}>₹{p.soldPrice}</span>}
                                </div>
                            </div>
                        </div>
                    ))
                ) : (
                    <div style={{ gridColumn: 'span 2', textAlign: 'center', padding: '40px', opacity: 0.5 }}>
                        No players drafted yet.
                    </div>
                )}
            </div>

            {/* Footer */}
            <div style={{ marginTop: '30px', borderTop: '1px solid rgba(255,255,255,0.1)', paddingTop: '15px', display: 'flex', justifyContent: 'space-between', fontSize: '0.9rem', opacity: 0.5 }}>
                <span>Generated by ProBid</span>
                <span>{new Date().toLocaleDateString()}</span>
            </div>
        </div>
    );
};

export default TeamExportCard;
